### ISSUE TITLE
create a gitbook to explain how to use these tools

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/github_automation#4]
- how to install a cockpit
- how to get access to this cockpit
- how to manually launch the ays services = the tool
- how to restart the portal
- how to see what works/doesn't work in the portal (actions)
- ...

**Comment by despiegk** [comment]
https://www.gitbook.com/book/gig/agiletools

**Comment by FastGeert** [comment]
Merged this FR with the documentation task
